// <auto-generated />
using System;
using HospiInHome.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospiInHome.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211014001427_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.HistoriaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Antecedentes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TratamientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TratamientoId");

                    b.ToTable("HistoriasClinicas");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("NombreMedicamento")
                        .HasColumnType("int");

                    b.Property<string>("Posologia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TratamientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TratamientoId");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Remision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resultado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoExamen")
                        .HasColumnType("int");

                    b.Property<int?>("TratamientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TratamientoId");

                    b.ToTable("Remisiones");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.SignoVital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("TipoSigno")
                        .HasColumnType("int");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("SignosVitales");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Tratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Incapacidad")
                        .HasColumnType("int");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tratamientos");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Enfermera", b =>
                {
                    b.HasBaseType("HospiInHome.App.Dominio.Entidades.Persona");

                    b.Property<string>("HorasLaborales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarjetaProfesional")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Enfermera");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.FamiliarDesignado", b =>
                {
                    b.HasBaseType("HospiInHome.App.Dominio.Entidades.Persona");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parentesco")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("FamiliarDesignado");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Medico", b =>
                {
                    b.HasBaseType("HospiInHome.App.Dominio.Entidades.Persona");

                    b.Property<string>("Especialidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistroMedico")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Medico");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Paciente", b =>
                {
                    b.HasBaseType("HospiInHome.App.Dominio.Entidades.Persona");

                    b.Property<int?>("EnfermeraId")
                        .HasColumnType("int");

                    b.Property<int?>("FamiliarDesignadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HistoriaClinicaId")
                        .HasColumnType("int");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<int?>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("PlanMedico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("EnfermeraId");

                    b.HasIndex("FamiliarDesignadoId");

                    b.HasIndex("HistoriaClinicaId");

                    b.HasIndex("MedicoId");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.HistoriaClinica", b =>
                {
                    b.HasOne("HospiInHome.App.Dominio.Entidades.Tratamiento", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("TratamientoId");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Medicamento", b =>
                {
                    b.HasOne("HospiInHome.App.Dominio.Entidades.Tratamiento", null)
                        .WithMany("Medicamentos")
                        .HasForeignKey("TratamientoId");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Remision", b =>
                {
                    b.HasOne("HospiInHome.App.Dominio.Entidades.Tratamiento", null)
                        .WithMany("Remisiones")
                        .HasForeignKey("TratamientoId");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.SignoVital", b =>
                {
                    b.HasOne("HospiInHome.App.Dominio.Entidades.Paciente", null)
                        .WithMany("SignosVitales")
                        .HasForeignKey("PacienteId");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Paciente", b =>
                {
                    b.HasOne("HospiInHome.App.Dominio.Entidades.Enfermera", "Enfermera")
                        .WithMany()
                        .HasForeignKey("EnfermeraId");

                    b.HasOne("HospiInHome.App.Dominio.Entidades.FamiliarDesignado", "FamiliarDesignado")
                        .WithMany()
                        .HasForeignKey("FamiliarDesignadoId");

                    b.HasOne("HospiInHome.App.Dominio.Entidades.HistoriaClinica", "HistoriaClinica")
                        .WithMany()
                        .HasForeignKey("HistoriaClinicaId");

                    b.HasOne("HospiInHome.App.Dominio.Entidades.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId");

                    b.Navigation("Enfermera");

                    b.Navigation("FamiliarDesignado");

                    b.Navigation("HistoriaClinica");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Tratamiento", b =>
                {
                    b.Navigation("Medicamentos");

                    b.Navigation("Remisiones");
                });

            modelBuilder.Entity("HospiInHome.App.Dominio.Entidades.Paciente", b =>
                {
                    b.Navigation("SignosVitales");
                });
#pragma warning restore 612, 618
        }
    }
}
